/* あとこれ v5 - いつものリスト */
let routines=[];
try{const s=JSON.parse(localStorage.getItem('atokoreTrialV4')||'null');routines=s?.routines||[]}catch(e){}

save=function(){try{localStorage.setItem('atokoreTrialV4',JSON.stringify({items,buys,routines}))}catch(e){}};

function routineEscape(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function routineStyles(){if(document.getElementById('routineStyles'))return;const s=document.createElement('style');s.id='routineStyles';s.textContent=`.routineTools{display:grid;grid-template-columns:1fr 1fr;gap:8px}.routineCard{border:1px solid #dfe4ea;border-radius:16px;padding:12px;margin:9px 0;background:#fff}.routineCardTop{display:flex;align-items:center;gap:10px}.routineCount{font-size:12px;color:#667085}.routineActions{display:flex;gap:8px;margin-top:10px}.routineActions .btn{flex:1}.routineCheck{width:22px;height:22px}.routineInline{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;margin:10px 0}.routineInline input{width:100%;padding:12px;border:1px solid #d9dee7;border-radius:12px;font-size:16px}.routineNameEdit{width:100%;padding:12px;border:1px solid #d9dee7;border-radius:12px;font-size:18px;font-weight:850}`;document.head.appendChild(s)}
function ensureRoutineUI(){const p=$('pg-buy');if(!p||$('routineList'))return;const d=document.createElement('div');d.innerHTML=`<div class="section">いつものリスト</div><div class="routineTools"><button class="btn ghost" onclick="newRoutine()">＋ 新しいリスト</button><button class="btn ghost" onclick="saveCurrentBuyAsRoutine()">今回の買い物を保存</button></div><div class="muted" style="margin-top:6px">よく買う組み合わせを保存して、必要な物だけまとめて追加できます。</div><div id="routineList"></div>`;p.appendChild(d)}
function renderRoutines(){const el=$('routineList');if(!el)return;if(!routines.length){el.innerHTML='<div class="empty" style="margin-top:10px">まだ「いつものリスト」はありません。<br>毎週の買い物やドラッグストア用などを作れます。</div>';return}el.innerHTML=routines.map(r=>`<div class="routineCard"><div class="routineCardTop"><div class="grow"><div class="name">${routineEscape(r.name)}</div><div class="routineCount">${r.items.length}商品</div></div><button class="btn ghost" onclick="openRoutine(${r.id})">開く</button></div><div class="routineActions"><button class="btn" onclick="addWholeRoutine(${r.id})">全部追加</button><button class="btn ghost" onclick="openRoutine(${r.id})">選んで追加</button></div></div>`).join('')}
const atokoreBaseRender=render;render=function(){atokoreBaseRender();ensureRoutineUI();renderRoutines()};
let routineSession={routineId:null,selected:new Set()};
function newRoutine(){openM(`<button class="close" onclick="closeM()">閉じる</button><h2>新しい「いつものリスト」</h2><div class="field"><div class="label">リスト名</div><input id="newRoutineName" placeholder="例：毎週の買い物"></div><button class="btn" style="width:100%" onclick="createRoutine()">作成する</button>`);setTimeout(()=>$('newRoutineName')?.focus(),120)}
function createRoutine(){const n=($('newRoutineName')?.value||'').trim();if(!n){alert('リスト名を入力してください');return}const id=Date.now();routines.push({id,name:n,items:[]});save();closeM();renderRoutines();openRoutine(id)}
function saveCurrentBuyAsRoutine(){if(!buys.length){alert('今回の買い物リストが空です');return}openM(`<button class="close" onclick="closeM()">閉じる</button><h2>今回の買い物を保存</h2><div class="field"><div class="label">リスト名</div><input id="saveRoutineName" placeholder="例：毎週の買い物"></div><div class="muted">${buys.length}商品を「いつものリスト」として保存します。</div><button class="btn" style="width:100%;margin-top:12px" onclick="confirmSaveCurrentBuy()">保存する</button>`);setTimeout(()=>$('saveRoutineName')?.focus(),120)}
function confirmSaveCurrentBuy(){const n=($('saveRoutineName')?.value||'').trim();if(!n){alert('リスト名を入力してください');return}const id=Date.now();routines.push({id,name:n,items:buys.map((b,i)=>({id:id+i+1,name:b.name,qty:b.qty,unit:b.unit}))});save();closeM();renderRoutines();alert('いつものリストに保存しました')}
function openRoutine(id,keep=false){const r=routines.find(x=>x.id===id);if(!r)return;if(!keep||routineSession.routineId!==id)routineSession={routineId:id,selected:new Set(r.items.map(x=>x.id))};openM(`<button class="close" onclick="closeM()">閉じる</button><h2>いつものリスト</h2><div class="field"><div class="label">リスト名</div><input class="routineNameEdit" id="routineNameEdit" value="${routineEscape(r.name)}"></div><button class="btn ghost" style="width:100%" onclick="saveRoutineName(${id})">名前を保存</button><div class="section">商品</div><div class="routineInline"><input id="routineAddName" placeholder="商品を追加（例：牛乳）"><button class="btn" onclick="routineAddItem(${id})">追加</button></div><div id="routineItems">${routineItemsHtml(r)}</div><div class="routineActions"><button class="btn ghost" onclick="routineSelectAll(${id})">全選択</button><button class="btn ghost" onclick="routineSelectNone(${id})">全解除</button></div><button class="btn" style="width:100%;margin-top:10px" onclick="addSelectedRoutine(${id})">チェックした商品を買い物へ</button><button class="btn danger" style="width:100%;margin-top:8px" onclick="deleteRoutine(${id})">このリストを削除</button>`)}
function routineItemsHtml(r){if(!r.items.length)return '<div class="empty">商品を追加してください</div>';return r.items.map(it=>`<div class="row"><input class="routineCheck" type="checkbox" ${routineSession.selected.has(it.id)?'checked':''} onchange="routineTogglePick(${it.id},this.checked)"><div class="grow"><div class="name">${routineEscape(it.name)}</div></div><div class="qty"><button class="icon" onclick="routineAdjust(${r.id},${it.id},-1)">−</button><b id="routineQty-${it.id}">${it.qty}${it.unit}</b><button class="icon" onclick="routineAdjust(${r.id},${it.id},1)">＋</button></div><button class="icon danger" onclick="routineRemoveItem(${r.id},${it.id})">×</button></div>`).join('')}
function routineTogglePick(id,on){on?routineSession.selected.add(id):routineSession.selected.delete(id)}
function routineSelectAll(id){const r=routines.find(x=>x.id===id);if(!r)return;routineSession.selected=new Set(r.items.map(x=>x.id));openRoutine(id,true)}
function routineSelectNone(id){routineSession.selected=new Set();openRoutine(id,true)}
function saveRoutineName(id){const r=routines.find(x=>x.id===id);if(!r)return;const n=($('routineNameEdit')?.value||'').trim();if(!n){alert('リスト名を入力してください');return}r.name=n;save();renderRoutines();alert('名前を変更しました')}
function routineAddItem(id){const r=routines.find(x=>x.id===id);if(!r)return;const n=($('routineAddName')?.value||'').trim();if(!n)return;const unit=unitOf(n),qty=buyStep(unit),iid=Date.now();r.items.push({id:iid,name:n,qty,unit});routineSession.selected.add(iid);save();openRoutine(id,true)}
function routineAdjust(rid,iid,d){const r=routines.find(x=>x.id===rid);if(!r)return;const it=r.items.find(x=>x.id===iid);if(!it)return;const step=buyStep(it.unit);it.qty=Math.max(step,it.qty+d*step);save();const q=$('routineQty-'+iid);if(q)q.textContent=`${it.qty}${it.unit}`}
function routineRemoveItem(rid,iid){const r=routines.find(x=>x.id===rid);if(!r)return;r.items=r.items.filter(x=>x.id!==iid);routineSession.selected.delete(iid);save();openRoutine(rid,true)}
function mergeRoutineBuy(n,q,u){let b=buys.find(x=>x.name===n&&x.unit===u);if(b)b.qty+=q;else buys.push({id:Date.now()+Math.floor(Math.random()*100000),name:n,qty:q,unit:u})}
function addWholeRoutine(id){const r=routines.find(x=>x.id===id);if(!r||!r.items.length){alert('商品がありません');return}r.items.forEach(it=>mergeRoutineBuy(it.name,it.qty,it.unit));save();render();alert(`${r.items.length}商品を買い物リストに追加しました`)}
function addSelectedRoutine(id){const r=routines.find(x=>x.id===id);if(!r)return;const a=r.items.filter(it=>routineSession.selected.has(it.id));if(!a.length){alert('追加する商品を選んでください');return}a.forEach(it=>mergeRoutineBuy(it.name,it.qty,it.unit));save();closeM();render();go('buy');alert(`${a.length}商品を買い物リストに追加しました`)}
function deleteRoutine(id){if(!confirm('この「いつものリスト」を削除しますか？'))return;routines=routines.filter(x=>x.id!==id);save();closeM();renderRoutines()}
routineStyles();ensureRoutineUI();const v5badge=document.querySelector('.badge');if(v5badge)v5badge.textContent='試用版 v5';renderRoutines();