/* あとこれ v12.5i - 商品名優先レシートOCR */
(()=>{
const css=`.receiptPick{border:1px dashed #b8c4d6;border-radius:16px;padding:14px;background:#f8fbff;text-align:center}.receiptSourceGrid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.receiptSourceBtn{position:relative;display:flex;align-items:center;justify-content:center;min-height:48px;padding:9px 7px;border:1px solid #cfe0f3;border-radius:12px;background:#fff;color:#1769aa;font-size:12px;font-weight:900;cursor:pointer}.receiptSourceBtn input{position:absolute!important;width:1px!important;height:1px!important;opacity:0;pointer-events:none}.receiptFileName{margin-top:9px;font-size:11px;color:#667085;overflow-wrap:anywhere}.receiptPreview{width:100%;max-height:260px;object-fit:contain;border-radius:12px;margin-top:10px;background:#f3f4f6}.receiptProgress{height:8px;background:#e9eef5;border-radius:999px;overflow:hidden;margin:10px 0}.receiptProgress>i{display:block;height:100%;width:0;background:#1677ff;transition:width .2s}.receiptReview{border:1px solid #dfe4ea;border-radius:15px;padding:10px;margin:10px 0;background:#fff}.receiptReview.low{border-color:#f6b44c;background:#fffaf0}.receiptCheck{width:22px;height:22px}.receiptGrid{display:grid;grid-template-columns:1fr 86px;gap:7px;margin-top:8px}.receiptGrid.three{grid-template-columns:1fr 90px 105px}.receiptGrid input,.receiptGrid select,.receiptMeta input{width:100%;padding:10px;border:1px solid #d9dee7;border-radius:10px;font-size:15px;background:#fff}.receiptOriginal{font-size:11px;color:#98a2b3;margin-top:5px;word-break:break-all}.receiptStatus{padding:10px 12px;border-radius:12px;background:#eef6ff;font-size:13px;margin:10px 0}.receiptWarn{background:#fff4e5;color:#8a4b00}.receiptRaw{width:100%;min-height:120px;padding:10px;border:1px solid #d9dee7;border-radius:10px;font-size:12px}.receiptMeta{display:grid;grid-template-columns:1fr 1fr;gap:8px}.receiptFoot{position:sticky;bottom:-26px;background:#fff;padding:10px 0 4px;border-top:1px solid #eef0f3}.receiptDelete{border:0;background:#fff0f0;color:#b42318;border-radius:9px;padding:7px 9px}@media(max-width:360px){.receiptSourceGrid{grid-template-columns:1fr}}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
let R={file:null,previewUrl:'',text:'',store:'',date:'',confidence:0,parsed:[]},loading=null;
const $r=id=>document.getElementById(id);
function fixedUnit(n){return /牛乳|低脂肪乳|豆乳|ミネラルウォーター|飲料水|ジュース|炭酸水|醤油|めんつゆ|白だし|料理酒|みりん|酢|洗剤|柔軟剤|ソープ|シャンプー/.test(n)?'本':/豚|鶏|牛肉|牛こま|牛薄切り|ひき肉|鮭|さば|ぶり|あじ|たら|肉|魚/.test(n)?'パック':/米$|お米|無洗米|小麦粉|片栗粉/.test(n)?'袋':/オムツ|パンツ|ゴミ袋|レジ袋|保存袋|防臭袋/.test(n)?'袋':/おしりふき|マスク|ナプキン|離乳食|ベビーフード/.test(n)?'パック':/ティッシュ/.test(n)?'箱':/卵/.test(n)?'個':'個'}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function openReceipt(){R={file:null,previewUrl:'',text:'',store:'',date:'',confidence:0,parsed:[]};openM(`<button class="close" onclick="closeReceiptV7()">閉じる</button><h2>🧾 レシート一括補充</h2><div class="receiptStatus">商品名だけをOCRで抽出します。金額・合計・商品コードなどの数字は在庫候補にしません。</div><div class="receiptPick"><div class="name">レシート画像を選ぶ</div><div class="muted" style="margin-top:5px">文字が正面から大きく写る画像がおすすめです。JPG・PNG・HEICなどの画像に対応します。</div><div class="receiptSourceGrid"><label class="receiptSourceBtn">📷 カメラで撮る<input id="receiptCamera" type="file" accept="image/*" capture="environment" onchange="receiptPickedV7(this)"></label><label class="receiptSourceBtn">🖼 写真・ファイルから選ぶ<input id="receiptFile" type="file" accept="image/*,.jpg,.jpeg,.png,.webp,.heic,.heif" onchange="receiptPickedV7(this)"></label></div><div id="receiptFileName" class="receiptFileName">まだ画像は選択されていません</div><img id="receiptPreview" class="receiptPreview hide" alt="選択したレシート画像"></div><div id="receiptProgressWrap" class="hide"><div id="receiptProgressText" class="muted" style="margin-top:10px">準備中…</div><div class="receiptProgress"><i id="receiptProgressBar"></i></div></div><button id="receiptAnalyzeBtn" class="btn" style="width:100%;margin-top:12px" onclick="analyzeReceiptV7()" disabled>商品名を解析</button><details class="detail" style="margin-top:12px"><summary>OCR文字を直接貼って解析</summary><div class="muted" style="margin:8px 0">読み取りにくい場合の予備機能です。ここでも商品名だけを抽出します。</div><textarea id="receiptManualText" class="receiptRaw" placeholder="レシートの文字を貼り付け"></textarea><button class="btn ghost" style="width:100%;margin-top:8px" onclick="analyzeReceiptTextV7()">商品名を解析</button></details>`)}
window.closeReceiptV7=()=>{if(R.previewUrl)URL.revokeObjectURL(R.previewUrl);closeM()};
window.receiptPickedV7=input=>{const f=input.files&&input.files[0];if(!f)return;const imageType=/^image\//i.test(f.type||''),imageName=/\.(?:jpe?g|png|webp|gif|bmp|heic|heif)$/i.test(f.name||'');if(!imageType&&!imageName){input.value='';alert('画像ファイルを選んでください（JPG・PNG・HEICなど）');return}R.file=f;if(R.previewUrl)URL.revokeObjectURL(R.previewUrl);R.previewUrl=URL.createObjectURL(f);const im=$r('receiptPreview');if(im){im.src=R.previewUrl;im.classList.remove('hide')}const n=$r('receiptFileName');if(n)n.textContent=`選択中：${f.name||'レシート画像'}`;const b=$r('receiptAnalyzeBtn');if(b)b.disabled=false};
function progress(label,p){const w=$r('receiptProgressWrap');if(w)w.classList.remove('hide');const t=$r('receiptProgressText');if(t)t.textContent=label;const b=$r('receiptProgressBar');if(b)b.style.width=`${Math.max(2,Math.min(100,Math.round((p||0)*100)))}%`}
function loadOCR(){if(window.Tesseract)return Promise.resolve();if(loading)return loading;loading=new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.async=true;s.onload=res;s.onerror=()=>rej(new Error('OCRライブラリ読込失敗'));document.head.appendChild(s)});return loading}
async function prep(f){const u=URL.createObjectURL(f);try{const im=new Image();await new Promise((res,rej)=>{im.onload=res;im.onerror=rej;im.src=u});const sc=Math.min(1,1800/im.naturalWidth,2600/im.naturalHeight),w=Math.max(1,Math.round(im.naturalWidth*sc)),h=Math.max(1,Math.round(im.naturalHeight*sc)),c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(im,0,0,w,h);const d=x.getImageData(0,0,w,h),p=d.data;for(let i=0;i<p.length;i+=4){const g=Math.round(p[i]*.299+p[i+1]*.587+p[i+2]*.114),v=Math.max(0,Math.min(255,Math.round((g-128)*1.35+145)));p[i]=p[i+1]=p[i+2]=v}x.putImageData(d,0,0);return c}finally{URL.revokeObjectURL(u)}}
window.analyzeReceiptV7=async()=>{if(!R.file){alert('レシートの写真または画像ファイルを選んでください');return}const b=$r('receiptAnalyzeBtn');if(b)b.disabled=true;try{progress('OCRを準備しています…',.03);await loadOCR();progress('画像を読みやすく調整しています…',.08);const c=await prep(R.file);const w=await Tesseract.createWorker('jpn+eng',Tesseract.OEM.LSTM,{logger:m=>{if(m.status==='recognizing text')progress(`商品名を読み取っています… ${Math.round((m.progress||0)*100)}%`,.12+(m.progress||0)*.82)}});await w.setParameters({preserve_interword_spaces:'1'});const z=await w.recognize(c);await w.terminate();R.text=z.data.text||'';R.confidence=Math.round(z.data.confidence||0);const p=parse(R.text);R.store=p.store;R.date=p.date;R.parsed=p.items;progress('商品名の解析完了',1);setTimeout(review,150)}catch(e){console.error(e);progress('解析に失敗しました',1);alert('解析に失敗しました。画像形式や通信状況を確認するか「OCR文字を直接貼って解析」を試してください。');if(b)b.disabled=false}};
window.analyzeReceiptTextV7=()=>{const t=($r('receiptManualText')?.value||'').trim();if(!t){alert('文字を貼り付けてください');return}R.text=t;R.confidence=0;const p=parse(t);R.store=p.store;R.date=p.date;R.parsed=p.items;review()};
function hw(s){return String(s||'').replace(/[０-９]/g,c=>String.fromCharCode(c.charCodeAt(0)-0xFEE0)).replace(/，/g,',').replace(/￥/g,'¥').replace(/×/g,'x')}
function key(s){return hw(s).normalize('NFKC').toLowerCase().replace(/[\s\-‐‑–—・･_*＊※#＃()（）\[\]【】「」『』:：.．,，/\\]/g,'')}
function aliases(){try{return JSON.parse(localStorage.getItem('atokoreReceiptAliases')||'{}')||{}}catch(e){return {}}}
function learn(raw,name){const k=key(raw);if(!k||!name)return;const a=aliases();a[k]=name;try{localStorage.setItem('atokoreReceiptAliases',JSON.stringify(a))}catch(e){}}
const rules=[[/玉子|たまご|タマゴ|卵/,'卵'],[/豚バラ(?!肉)/,'豚バラ肉'],[/豚こま/,'豚こま肉'],[/鶏もも/,'鶏もも肉'],[/鶏むね/,'鶏むね肉'],[/牛乳|おいしいミルク|メグミルク|乳飲料/,'牛乳'],[/豆乳/,'豆乳'],[/食パン|超熟|本仕込/,'食パン'],[/ヨーグルト|ヨーグル/,'ヨーグルト'],[/納豆/,'納豆'],[/豆腐/,'豆腐'],[/バナナ/,'バナナ'],[/りんご|リンゴ/,'りんご'],[/みかん|ミカン/,'みかん'],[/トイレット.*ペーパー|トイレ.*ロール/,'トイレットペーパー'],[/箱?ティッシュ|ティシュ/,'ティッシュ'],[/キッチン.*ペーパー/,'キッチンペーパー'],[/おしり.*ふき/,'おしりふき'],[/おむつ|オムツ|紙パンツ/,'オムツ'],[/柔軟剤/,'柔軟剤'],[/食器.*洗剤/,'食器用洗剤'],[/洗濯.*洗剤|衣料.*洗剤/,'洗濯洗剤'],[/シャンプー/,'シャンプー'],[/コンディショナー|リンス/,'コンディショナー'],[/ボディ.*ソープ/,'ボディソープ'],[/ハンド.*ソープ/,'ハンドソープ'],[/マスク/,'マスク'],[/歯ブラシ/,'歯ブラシ'],[/歯磨|ハミガキ/,'歯磨き粉'],[/ミネラル.*ウォーター|天然水/,'ミネラルウォーター'],[/麦茶/,'麦茶'],[/コーヒー|珈琲/,'コーヒー'],[/冷凍.*餃子/,'冷凍餃子'],[/冷凍.*からあげ|冷凍.*唐揚/,'冷凍からあげ']];
function canon(raw){const c=hw(raw).replace(/^[*＊※#\s]+/,'').replace(/\s+/g,' ').trim(),k=key(c),l=aliases()[k];if(l)return l;for(const [r,n] of rules)if(r.test(c))return n;let best='';for(const arr of Object.values(C))for(const n of arr){const nk=key(n);if(nk&&k.includes(nk)&&nk.length>key(best).length)best=n}return best||c.slice(0,34)||'商品'}
function cat(n,r=''){for(const [c,a] of Object.entries(C))if(a.includes(n))return c;const s=n+' '+r;if(/オムツ|おしりふき|ミルク|離乳食|ベビー/.test(s))return 'ベビー';if(/洗剤|柔軟剤|ティッシュ|ペーパー|ラップ|スポンジ|ゴミ袋|シャンプー|ソープ|掃除/.test(s))return '日用品';if(/薬|マスク|歯ブラシ|歯磨|ナプキン|消毒|絆創膏|湿布/.test(s))return '衛生・薬';if(/電池|電球|ケーブル|フィルター|カセットボンベ/.test(s))return '家電・生活用品';if(/非常|防災|簡易トイレ|アルファ米/.test(s))return '防災';return /[ぁ-んァ-ヶ一-龠]/.test(s)?'食料品':'その他'}
function place(n,c){if(/冷凍/.test(n))return '冷凍庫';if(/牛乳|豆乳|卵|ヨーグルト|チーズ|バター|生クリーム|納豆|豆腐|油揚げ|厚揚げ|豚|鶏|牛肉|ひき肉|鮭|さば|ぶり|あじ|たら|レタス|白菜|きゅうり|トマト|ほうれん草|小松菜|ブロッコリー|もやし|きのこ/.test(n))return '冷蔵庫';return c==='食料品'?'パントリー':c==='防災'?'防災収納':'収納'}
function noise(l){return /合計|小計|税込|税抜|消費税|内税|外税|税率|お預|預り|お釣|釣銭|おつり|クレジット|電子マネー|ポイント|値引|割引|クーポン|レジ(?:No|番号|担当|係|$)|担当|TEL|電話|領収|商品点数|買上点数|商品コード|商品番号|品番|現金|カード|支払|決済|対象額|本体価格|お会計|レシート|取引|会員|バーコード|JAN|登録番号|インボイス|営業時間|住所|郵便|毎度|ありがとう|返品|交換|伝票|発行日時/.test(l)}
function productText(raw){return hw(raw).normalize('NFKC').replace(/^[*＊※#＃\s]+/,'').replace(/^(?:(?:JAN|商品(?:コード|番号)|品番|No\.?)\s*[:：]?\s*)?\d{5,}\s*/i,'').replace(/\b\d{7,}\b/g,' ').replace(/(\d+(?:\.\d+)?)\s+(ml|l|g|kg|個入|本入|枚入|袋入|パック)(?=\s|$)/gi,'$1$2').replace(/\s+(?:単価|@)\s*¥?\s*\d[\d,]*(?:\s*円)?(?:\s*[x×]\s*\d{1,3})?\s*$/i,'').replace(/\s+(?:x|X|×)\s*\d{1,3}\s*$/,'').replace(/\s+\d{1,3}\s*点\s*$/,'').replace(/(?:^|\s)\d{1,6}(?=\s|$)/g,' ').replace(/\s+/g,' ').trim()}
function hasProductName(s){const letters=s.match(/[A-Za-zぁ-んァ-ヶ一-龠々ー]/g)||[];return letters.length>=2||/^(?:米|卵|麺|塩|酢|油|茶)$/.test(s)||(/[A-Za-z]/.test(s)&&/\d/.test(s)&&/^[A-Za-z0-9+\-_.\s]+$/.test(s))}
function parse(text){let ls=hw(text).split(/\r?\n/).map(x=>x.replace(/[\t　]+/g,' ').replace(/\s+/g,' ').trim()).filter(Boolean),joined=[];const onlyMoney=/^[¥]?\s*\d{1,6}(?:\s*円)?\s*[*＊]?$/;const moneyTail=/(?:^|\s|¥)(?:¥\s*)?(\d{1,3}(?:,\d{3})+|\d{1,6})(?:\s*円)?\s*[*＊]?$/;for(let i=0;i<ls.length;i++){const a=ls[i],b=ls[i+1]||'';if(!moneyTail.test(a)&&onlyMoney.test(b)){joined.push(a+' '+b);i++}else joined.push(a)}const out=[];for(const line of joined){if(noise(line)||/(?:20\d{2}|\b\d{2})[\/\-.年]\d{1,2}[\/\-.月]\d{1,2}|\b\d{1,2}:\d{2}(?::\d{2})?\b|〒\s*\d{3}[-ー]\d{4}/.test(line))continue;const money=line.match(moneyTail);if(!money)continue;const raw=productText(line.slice(0,money.index));if(!raw||noise(raw)||!hasProductName(raw))continue;const name=canon(raw);if(!hasProductName(name))continue;const c=cat(name,raw),item={selected:true,raw,name,qty:1,unit:fixedUnit(name),cat:c,price:0,total:0,place:place(name,c)};const duplicate=out.some(x=>key(x.name)===key(item.name));if(!duplicate)out.push(item)}return {store:'',date:today(),items:out.slice(0,60)}}
function opts(cur,a){return a.map(v=>`<option ${v===cur?'selected':''}>${v}</option>`).join('')}
window.receiptUpdateV7=(i,k,v)=>{const x=R.parsed[i];if(!x)return;if(k==='qty')v=+v||0;x[k]=v;if(k==='name'){x.cat=cat(v,x.raw);x.unit=fixedUnit(v);x.place=place(v,x.cat)}count()};window.receiptToggleV7=(i,on)=>{if(R.parsed[i])R.parsed[i].selected=on;count()};window.receiptDeleteV7=i=>{R.parsed.splice(i,1);review()};window.receiptAddV7=()=>{R.parsed.push({selected:true,raw:'',name:'',qty:1,unit:'個',cat:'食料品',price:0,total:0,place:'パントリー',low:true});review()};
function row(x,i){const cs=['食料品','日用品','衛生・薬','ベビー','子ども','衣類','家電・生活用品','防災','その他'],us=['個','本','袋','箱','パック','枚'];return `<div class="receiptReview ${x.low?'low':''}"><div style="display:flex;gap:9px;align-items:center"><input class="receiptCheck" type="checkbox" ${x.selected?'checked':''} onchange="receiptToggleV7(${i},this.checked)"><div class="grow"><div class="label">商品名</div><input style="width:100%;padding:10px;border:1px solid #d9dee7;border-radius:10px;font-size:16px" value="${esc(x.name)}" onchange="receiptUpdateV7(${i},'name',this.value)"></div><button class="receiptDelete" onclick="receiptDeleteV7(${i})">削除</button></div><div class="receiptGrid three"><div><div class="label">数量</div><input type="number" min="0" step="any" value="${x.qty}" onchange="receiptUpdateV7(${i},'qty',this.value)"></div><div><div class="label">単位</div><select onchange="receiptUpdateV7(${i},'unit',this.value)">${opts(x.unit,us)}</select></div><div><div class="label">カテゴリー</div><select onchange="receiptUpdateV7(${i},'cat',this.value)">${opts(x.cat,cs)}</select></div></div>${x.raw?`<div class="receiptOriginal">読み取った商品名: ${esc(x.raw)}</div>`:''}</div>`}
window.receiptStoreV124=v=>{R.store=v};window.receiptDateV124=v=>{R.date=v};
function review(){openM(`<button class="close" onclick="closeReceiptV7()">閉じる</button><h2>🧾 商品名を確認</h2><div class="receiptStatus ${R.confidence&&R.confidence<65?'receiptWarn':''}">${R.confidence?`OCR信頼度 ${R.confidence}%・`:''}${R.parsed.length}件の商品名候補を見つけました。数字情報は使わず、数量はすべて1から始めています。</div><div class="section">商品名候補</div>${R.parsed.length?R.parsed.map(row).join(''):'<div class="empty">商品名候補を抽出できませんでした。下の「商品を追加」から入力できます。</div>'}<button class="btn ghost" style="width:100%;margin-top:8px" onclick="receiptAddV7()">＋ 商品を追加</button><details class="detail" style="margin-top:12px"><summary>OCRした元の文字を見る</summary><textarea class="receiptRaw" readonly>${esc(R.text)}</textarea></details><div class="receiptFoot"><label class="row" style="margin:0 0 8px"><input id="receiptRemoveBuy" type="checkbox" checked style="width:20px;height:20px"><div class="grow"><div class="name">買い物リストも整理</div><div class="meta">登録した商品を今回の買い物リストから消す</div></div></label><button id="receiptApplyBtn" class="btn" style="width:100%" onclick="receiptApplyV7()">在庫へ追加</button></div>`);count()}
function count(){const n=R.parsed.filter(x=>x.selected&&String(x.name||'').trim()&&+x.qty>0).length,b=$r('receiptApplyBtn');if(b)b.textContent=`選択した${n}件を在庫へ追加`}
window.receiptApplyV7=()=>{const a=R.parsed.filter(x=>x.selected&&String(x.name||'').trim()&&+x.qty>0);if(!a.length){alert('登録する商品を選んでください');return}const base=Date.now();a.forEach((r,i)=>{const name=String(r.name).trim(),qty=+r.qty||1,unit=r.unit||fixedUnit(name),c=r.cat||cat(name,r.raw),pl=r.place||place(name,c);let x=items.find(v=>v.name===name&&v.unit===unit);if(x){x.qty=(+x.qty||0)+qty;x.purchase=today();x.usage=(x.usage||0)+1}else items.push({id:base+i,name,cat:c,qty,unit,purchase:today(),price:0,store:'',place:pl,expType:'期限なし',exp:'',memo:'レシートOCRから登録',usage:1});if(r.raw)learn(r.raw,name)});if($r('receiptRemoveBuy')?.checked){const names=new Set(a.map(x=>String(x.name).trim()));buys=buys.filter(b=>!names.has(b.name))}save();render();closeReceiptV7();go('stock');alert(`${a.length}件を在庫へ反映しました`)};
window.__atokoreReceiptV125I={parseProductNames:parse,cleanProductName:productText};
const baseShow=showPremium;showPremium=function(k){if(k==='receipt')return openReceipt();if(k==='money'){const v=items.reduce((s,x)=>s+(Number.isFinite(x.purchaseTotal)?x.purchaseTotal:(x.price||0)*Math.max(1,x.qty||1)),0);return openM(`<button class="close" onclick="closeM()">閉じる</button><h2>💰 節約レポート</h2><div class="metrics"><div class="metric"><b>¥${v.toLocaleString()}</b><span class="muted">推定在庫金額</span></div><div class="metric"><b>${items.filter(x=>x.price>0).length}</b><span class="muted">価格記録</span></div><div class="metric"><b>${items.length}</b><span class="muted">登録品</span></div></div>`)}return baseShow(k)};
const badge=document.querySelector('.badge');if(badge)badge.textContent='試用版 v12.5i';const prem=[...document.querySelectorAll('#pg-premium .premium')].find(x=>x.textContent.includes('レシート一括補充'));if(prem){const m=prem.querySelector('.meta');if(m)m.textContent='写真から商品名だけ抽出→確認→在庫反映'}
})();
