/* あとこれ v7 - 実レシートOCR */
(()=>{
const css=`.receiptPick{border:1px dashed #b8c4d6;border-radius:16px;padding:14px;background:#f8fbff;text-align:center}.receiptPick input{width:100%;font-size:16px}.receiptPreview{width:100%;max-height:260px;object-fit:contain;border-radius:12px;margin-top:10px;background:#f3f4f6}.receiptProgress{height:8px;background:#e9eef5;border-radius:999px;overflow:hidden;margin:10px 0}.receiptProgress>i{display:block;height:100%;width:0;background:#1677ff;transition:width .2s}.receiptReview{border:1px solid #dfe4ea;border-radius:15px;padding:10px;margin:10px 0;background:#fff}.receiptReview.low{border-color:#f6b44c;background:#fffaf0}.receiptCheck{width:22px;height:22px}.receiptGrid{display:grid;grid-template-columns:1fr 86px;gap:7px;margin-top:8px}.receiptGrid.three{grid-template-columns:1fr 90px 105px}.receiptGrid input,.receiptGrid select,.receiptMeta input{width:100%;padding:10px;border:1px solid #d9dee7;border-radius:10px;font-size:15px;background:#fff}.receiptOriginal{font-size:11px;color:#98a2b3;margin-top:5px;word-break:break-all}.receiptStatus{padding:10px 12px;border-radius:12px;background:#eef6ff;font-size:13px;margin:10px 0}.receiptWarn{background:#fff4e5;color:#8a4b00}.receiptRaw{width:100%;min-height:120px;padding:10px;border:1px solid #d9dee7;border-radius:10px;font-size:12px}.receiptMeta{display:grid;grid-template-columns:1fr 1fr;gap:8px}.receiptFoot{position:sticky;bottom:-26px;background:#fff;padding:10px 0 4px;border-top:1px solid #eef0f3}.receiptDelete{border:0;background:#fff0f0;color:#b42318;border-radius:9px;padding:7px 9px}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
let R={file:null,previewUrl:'',text:'',store:'',date:'',confidence:0,parsed:[]},loading=null;
const $r=id=>document.getElementById(id);
function fixedUnit(n){return /牛乳|低脂肪乳|豆乳|ミネラルウォーター|飲料水|ジュース|炭酸水|醤油|めんつゆ|白だし|料理酒|みりん|酢|洗剤|柔軟剤|ソープ|シャンプー/.test(n)?'本':/豚|鶏|牛肉|牛こま|牛薄切り|ひき肉|鮭|さば|ぶり|あじ|たら|肉|魚/.test(n)?'パック':/米$|お米|無洗米|小麦粉|片栗粉/.test(n)?'袋':/オムツ|パンツ|ゴミ袋|レジ袋|保存袋|防臭袋/.test(n)?'袋':/おしりふき|マスク|ナプキン|離乳食|ベビーフード/.test(n)?'パック':/ティッシュ/.test(n)?'箱':/卵/.test(n)?'個':'個'}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function openReceipt(){R={file:null,previewUrl:'',text:'',store:'',date:'',confidence:0,parsed:[]};openM(`<button class="close" onclick="closeReceiptV7()">閉じる</button><h2>🧾 レシート一括補充</h2><div class="receiptStatus">レシートを撮影または写真から選択すると、端末上でOCRして商品候補を作ります。登録前に必ず内容を確認できます。</div><div class="receiptPick"><div class="name">レシート写真</div><div class="muted" style="margin:5px 0 10px">文字が正面から大きく写るように撮ると精度が上がります。</div><input id="receiptFile" type="file" accept="image/*" capture="environment" onchange="receiptPickedV7(this)"><img id="receiptPreview" class="receiptPreview hide" alt="レシート画像"></div><div id="receiptProgressWrap" class="hide"><div id="receiptProgressText" class="muted" style="margin-top:10px">準備中…</div><div class="receiptProgress"><i id="receiptProgressBar"></i></div></div><button id="receiptAnalyzeBtn" class="btn" style="width:100%;margin-top:12px" onclick="analyzeReceiptV7()" disabled>このレシートを解析</button><details class="detail" style="margin-top:12px"><summary>OCR文字を直接貼って解析</summary><div class="muted" style="margin:8px 0">読み取りにくい場合の予備機能です。</div><textarea id="receiptManualText" class="receiptRaw" placeholder="レシートの文字を貼り付け"></textarea><button class="btn ghost" style="width:100%;margin-top:8px" onclick="analyzeReceiptTextV7()">貼り付けた文字を解析</button></details>`)}
window.closeReceiptV7=()=>{if(R.previewUrl)URL.revokeObjectURL(R.previewUrl);closeM()};
window.receiptPickedV7=input=>{const f=input.files&&input.files[0];if(!f)return;R.file=f;if(R.previewUrl)URL.revokeObjectURL(R.previewUrl);R.previewUrl=URL.createObjectURL(f);const im=$r('receiptPreview');if(im){im.src=R.previewUrl;im.classList.remove('hide')}const b=$r('receiptAnalyzeBtn');if(b)b.disabled=false};
function progress(label,p){const w=$r('receiptProgressWrap');if(w)w.classList.remove('hide');const t=$r('receiptProgressText');if(t)t.textContent=label;const b=$r('receiptProgressBar');if(b)b.style.width=`${Math.max(2,Math.min(100,Math.round((p||0)*100)))}%`}
function loadOCR(){if(window.Tesseract)return Promise.resolve();if(loading)return loading;loading=new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.async=true;s.onload=res;s.onerror=()=>rej(new Error('OCRライブラリ読込失敗'));document.head.appendChild(s)});return loading}
async function prep(f){const u=URL.createObjectURL(f);try{const im=new Image();await new Promise((res,rej)=>{im.onload=res;im.onerror=rej;im.src=u});const sc=Math.min(1,1800/im.naturalWidth,2600/im.naturalHeight),w=Math.max(1,Math.round(im.naturalWidth*sc)),h=Math.max(1,Math.round(im.naturalHeight*sc)),c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(im,0,0,w,h);const d=x.getImageData(0,0,w,h),p=d.data;for(let i=0;i<p.length;i+=4){const g=Math.round(p[i]*.299+p[i+1]*.587+p[i+2]*.114),v=Math.max(0,Math.min(255,Math.round((g-128)*1.35+145)));p[i]=p[i+1]=p[i+2]=v}x.putImageData(d,0,0);return c}finally{URL.revokeObjectURL(u)}}
window.analyzeReceiptV7=async()=>{if(!R.file){alert('レシート写真を選んでください');return}const b=$r('receiptAnalyzeBtn');if(b)b.disabled=true;try{progress('OCRを準備しています…',.03);await loadOCR();progress('画像を読みやすく調整しています…',.08);const c=await prep(R.file);const w=await Tesseract.createWorker('jpn+eng',Tesseract.OEM.LSTM,{logger:m=>{if(m.status==='recognizing text')progress(`文字を読み取っています… ${Math.round((m.progress||0)*100)}%`,.12+(m.progress||0)*.82)}});await w.setParameters({preserve_interword_spaces:'1'});const z=await w.recognize(c);await w.terminate();R.text=z.data.text||'';R.confidence=Math.round(z.data.confidence||0);const p=parse(R.text);R.store=p.store;R.date=p.date;R.parsed=p.items;progress('解析完了',1);setTimeout(review,150)}catch(e){console.error(e);progress('解析に失敗しました',1);alert('解析に失敗しました。通信状況を確認するか「OCR文字を直接貼って解析」を試してください。');if(b)b.disabled=false}};
window.analyzeReceiptTextV7=()=>{const t=($r('receiptManualText')?.value||'').trim();if(!t){alert('文字を貼り付けてください');return}R.text=t;R.confidence=0;const p=parse(t);R.store=p.store;R.date=p.date;R.parsed=p.items;review()};
function hw(s){return String(s||'').replace(/[０-９]/g,c=>String.fromCharCode(c.charCodeAt(0)-0xFEE0)).replace(/，/g,',').replace(/￥/g,'¥').replace(/×/g,'x')}
function key(s){return hw(s).normalize('NFKC').toLowerCase().replace(/[\s\-‐‑–—・･_*＊※#＃()（）\[\]【】「」『』:：.．,，/\\]/g,'')}
function aliases(){try{return JSON.parse(localStorage.getItem('atokoreReceiptAliases')||'{}')||{}}catch(e){return {}}}
function learn(raw,name){const k=key(raw);if(!k||!name)return;const a=aliases();a[k]=name;try{localStorage.setItem('atokoreReceiptAliases',JSON.stringify(a))}catch(e){}}
const rules=[[/玉子|たまご|タマゴ|卵/,'卵'],[/豚バラ(?!肉)/,'豚バラ肉'],[/豚こま/,'豚こま肉'],[/鶏もも/,'鶏もも肉'],[/鶏むね/,'鶏むね肉'],[/牛乳|おいしいミルク|メグミルク|乳飲料/,'牛乳'],[/豆乳/,'豆乳'],[/食パン|超熟|本仕込/,'食パン'],[/ヨーグルト|ヨーグル/,'ヨーグルト'],[/納豆/,'納豆'],[/豆腐/,'豆腐'],[/バナナ/,'バナナ'],[/りんご|リンゴ/,'りんご'],[/みかん|ミカン/,'みかん'],[/トイレット.*ペーパー|トイレ.*ロール/,'トイレットペーパー'],[/箱?ティッシュ|ティシュ/,'ティッシュ'],[/キッチン.*ペーパー/,'キッチンペーパー'],[/おしり.*ふき/,'おしりふき'],[/おむつ|オムツ|紙パンツ/,'オムツ'],[/柔軟剤/,'柔軟剤'],[/食器.*洗剤/,'食器用洗剤'],[/洗濯.*洗剤|衣料.*洗剤/,'洗濯洗剤'],[/シャンプー/,'シャンプー'],[/コンディショナー|リンス/,'コンディショナー'],[/ボディ.*ソープ/,'ボディソープ'],[/ハンド.*ソープ/,'ハンドソープ'],[/マスク/,'マスク'],[/歯ブラシ/,'歯ブラシ'],[/歯磨|ハミガキ/,'歯磨き粉'],[/ミネラル.*ウォーター|天然水/,'ミネラルウォーター'],[/麦茶/,'麦茶'],[/コーヒー|珈琲/,'コーヒー'],[/冷凍.*餃子/,'冷凍餃子'],[/冷凍.*からあげ|冷凍.*唐揚/,'冷凍からあげ']];
function canon(raw){const c=hw(raw).replace(/^[*＊※#\s]+/,'').replace(/\s+/g,' ').trim(),k=key(c),l=aliases()[k];if(l)return l;for(const [r,n] of rules)if(r.test(c))return n;let best='';for(const arr of Object.values(C))for(const n of arr){const nk=key(n);if(nk&&k.includes(nk)&&nk.length>key(best).length)best=n}return best||c.replace(/\b\d+(?:\.\d+)?\s*(?:ml|mL|l|L|g|kg)\b/gi,'').trim().slice(0,34)||'商品'}
function cat(n,r=''){for(const [c,a] of Object.entries(C))if(a.includes(n))return c;const s=n+' '+r;if(/オムツ|おしりふき|ミルク|離乳食|ベビー/.test(s))return 'ベビー';if(/洗剤|柔軟剤|ティッシュ|ペーパー|ラップ|スポンジ|ゴミ袋|シャンプー|ソープ|掃除/.test(s))return '日用品';if(/薬|マスク|歯ブラシ|歯磨|ナプキン|消毒|絆創膏|湿布/.test(s))return '衛生・薬';if(/電池|電球|ケーブル|フィルター|カセットボンベ/.test(s))return '家電・生活用品';if(/非常|防災|簡易トイレ|アルファ米/.test(s))return '防災';return /[ぁ-んァ-ヶ一-龠]/.test(s)?'食料品':'その他'}
function qUnit(n,r){const s=hw(r),base=fixedUnit(n),x=s.match(/(?:x|X)\s*(\d{1,3})\b|\b(\d{1,3})\s*点\b/);if(x)return {qty:+(x[1]||x[2])||1,unit:base,count:true};if(/卵/.test(n)){const e=s.match(/(\d{1,2})\s*個(?:入)?/);if(e)return {qty:+e[1],unit:'個',count:true}}return {qty:1,unit:base,count:false}}
function place(n,c){if(/冷凍/.test(n))return '冷凍庫';if(/牛乳|豆乳|卵|ヨーグルト|チーズ|バター|生クリーム|納豆|豆腐|油揚げ|厚揚げ|豚|鶏|牛肉|ひき肉|鮭|さば|ぶり|あじ|たら|レタス|白菜|きゅうり|トマト|ほうれん草|小松菜|ブロッコリー|もやし|きのこ/.test(n))return '冷蔵庫';return c==='食料品'?'パントリー':c==='防災'?'防災収納':'収納'}
function noise(l){return /合計|小計|税込|税抜|消費税|内税|外税|税率|お預|預り|お釣|釣銭|おつり|クレジット|電子マネー|ポイント|値引|割引|クーポン|レジ|担当|TEL|電話|領収|商品点数|買上点数|現金|カード|支払|決済|対象額|本体価格|お会計|レシートNo|取引No|会員|バーコード/.test(l)}
function dateOf(t){const s=hw(t);let m=s.match(/(20\d{2})[\/\-.年]\s*(\d{1,2})[\/\-.月]\s*(\d{1,2})日?/);if(!m)m=s.match(/\b(\d{2})[\/\-.](\d{1,2})[\/\-.](\d{1,2})\b/);if(!m)return today();let y=+m[1];if(y<100)y+=2000;return `${y}-${String(+m[2]).padStart(2,'0')}-${String(+m[3]).padStart(2,'0')}`}
function parse(text){let ls=hw(text).split(/\r?\n/).map(x=>x.replace(/[\t　]+/g,' ').replace(/\s+/g,' ').trim()).filter(Boolean),j=[];for(let i=0;i<ls.length;i++){const a=ls[i],b=ls[i+1]||'',op=/^[¥]?\s*\d{2,6}(?:\s*円)?\s*[*＊]?$/.test(b),hp=/(?:¥\s*)?(\d{1,3}(?:,\d{3})+|\d{2,6})(?:\s*円)?\s*[*＊]?$/.test(a);if(!hp&&op){j.push(a+' '+b);i++}else j.push(a)}ls=j;const store=(ls.slice(0,10).filter(x=>!noise(x)&&!/20\d{2}[\/\-.年]|\d{1,2}:\d{2}|TEL|電話|〒|レシート|領収/.test(x)).find(x=>/[一-龠ぁ-んァ-ヶA-Za-z]{2,}/.test(x))||'').slice(0,40),out=[];for(const l of ls){if(noise(l)||/(?:20\d{2}|\b\d{2})[\/\-.年]\d{1,2}[\/\-.月]\d{1,2}|\b\d{1,2}:\d{2}(?::\d{2})?\b/.test(l))continue;const m=l.match(/(?:¥\s*)?(\d{1,3}(?:,\d{3})+|\d{2,6})(?:\s*円)?\s*[*＊]?$/);if(!m)continue;const total=+m[1].replace(/,/g,'');if(!total||total>999999)continue;let raw=l.slice(0,m.index).replace(/^[*＊※#\s]+/,'').trim();if(!raw||noise(raw)||/^\d+$/.test(raw))continue;const name=canon(raw),q=qUnit(name,raw),c=cat(name,raw),price=q.count&&q.qty>1?Math.max(1,Math.round(total/q.qty)):total;out.push({selected:true,raw,name,qty:q.qty,unit:q.unit,cat:c,price,total,place:place(name,c)})}const d=[];for(const x of out)if(!d.some(y=>y.raw===x.raw&&y.total===x.total))d.push(x);return {store,date:dateOf(text),items:d.slice(0,60)}}
function opts(cur,a){return a.map(v=>`<option ${v===cur?'selected':''}>${v}</option>`).join('')}
window.receiptUpdateV7=(i,k,v)=>{const x=R.parsed[i];if(!x)return;if(k==='qty'||k==='price')v=+v||0;x[k]=v;if(k==='name'){x.cat=cat(v,x.raw);x.unit=fixedUnit(v);x.place=place(v,x.cat)}count()};window.receiptToggleV7=(i,on)=>{if(R.parsed[i])R.parsed[i].selected=on;count()};window.receiptDeleteV7=i=>{R.parsed.splice(i,1);review()};window.receiptAddV7=()=>{R.parsed.push({selected:true,raw:'',name:'',qty:1,unit:'個',cat:'食料品',price:0,total:0,place:'パントリー',low:true});review()};
function row(x,i){const cs=['食料品','日用品','衛生・薬','ベビー','子ども','衣類','家電・生活用品','防災','その他'],us=['個','本','袋','箱','パック','枚'];return `<div class="receiptReview ${x.low?'low':''}"><div style="display:flex;gap:9px;align-items:center"><input class="receiptCheck" type="checkbox" ${x.selected?'checked':''} onchange="receiptToggleV7(${i},this.checked)"><div class="grow"><div class="label">商品名</div><input style="width:100%;padding:10px;border:1px solid #d9dee7;border-radius:10px;font-size:16px" value="${esc(x.name)}" onchange="receiptUpdateV7(${i},'name',this.value)"></div><button class="receiptDelete" onclick="receiptDeleteV7(${i})">削除</button></div><div class="receiptGrid three"><div><div class="label">数量</div><input type="number" min="0" step="any" value="${x.qty}" onchange="receiptUpdateV7(${i},'qty',this.value)"></div><div><div class="label">単位</div><select onchange="receiptUpdateV7(${i},'unit',this.value)">${opts(x.unit,us)}</select></div><div><div class="label">カテゴリー</div><select onchange="receiptUpdateV7(${i},'cat',this.value)">${opts(x.cat,cs)}</select></div></div><div class="receiptGrid"><div><div class="label">購入単価</div><input type="number" value="${x.price||0}" onchange="receiptUpdateV7(${i},'price',this.value)"></div><div><div class="label">レシート金額</div><input value="¥${Number(x.total||0).toLocaleString()}" disabled></div></div>${x.raw?`<div class="receiptOriginal">OCR: ${esc(x.raw)}</div>`:''}</div>`}
window.receiptStoreV124=v=>{R.store=v};window.receiptDateV124=v=>{R.date=v};
function review(){openM(`<button class="close" onclick="closeReceiptV7()">閉じる</button><h2>🧾 解析結果を確認</h2><div class="receiptStatus ${R.confidence&&R.confidence<65?'receiptWarn':''}">${R.confidence?`OCR信頼度 ${R.confidence}%・`:''}${R.parsed.length}件の候補を見つけました。誤読があれば直してから登録してください。</div><div class="receiptMeta"><div><div class="label">購入店舗</div><input value="${esc(R.store)}" onchange="receiptStoreV124(this.value)"></div><div><div class="label">購入日</div><input type="date" value="${esc(R.date||today())}" onchange="receiptDateV124(this.value)"></div></div><div class="section">商品候補</div>${R.parsed.length?R.parsed.map(row).join(''):'<div class="empty">商品候補を抽出できませんでした。</div>'}<button class="btn ghost" style="width:100%;margin-top:8px" onclick="receiptAddV7()">＋ 商品を追加</button><details class="detail" style="margin-top:12px"><summary>OCRした元の文字を見る</summary><textarea class="receiptRaw" readonly>${esc(R.text)}</textarea></details><div class="receiptFoot"><label class="row" style="margin:0 0 8px"><input id="receiptRemoveBuy" type="checkbox" checked style="width:20px;height:20px"><div class="grow"><div class="name">買い物リストも整理</div><div class="meta">登録した商品を今回の買い物リストから消す</div></div></label><button id="receiptApplyBtn" class="btn" style="width:100%" onclick="receiptApplyV7()">在庫へ追加</button></div>`);count()}
function count(){const n=R.parsed.filter(x=>x.selected&&String(x.name||'').trim()&&+x.qty>0).length,b=$r('receiptApplyBtn');if(b)b.textContent=`選択した${n}件を在庫へ追加`}
window.receiptApplyV7=()=>{const a=R.parsed.filter(x=>x.selected&&String(x.name||'').trim()&&+x.qty>0);if(!a.length){alert('登録する商品を選んでください');return}const base=Date.now();a.forEach((r,i)=>{const name=String(r.name).trim(),qty=+r.qty||1,unit=r.unit||fixedUnit(name),c=r.cat||cat(name,r.raw),pl=r.place||place(name,c);let x=items.find(v=>v.name===name&&v.unit===unit);if(x){x.qty=(+x.qty||0)+qty;x.purchase=R.date||today();x.store=R.store||x.store||'';if(r.price)x.price=+r.price;x.purchaseTotal=+r.total||undefined;x.usage=(x.usage||0)+1}else items.push({id:base+i,name,cat:c,qty,unit,purchase:R.date||today(),price:+r.price||0,purchaseTotal:+r.total||undefined,store:R.store||'',place:pl,expType:'期限なし',exp:'',memo:'レシートOCRから登録',usage:1});if(r.raw)learn(r.raw,name)});if($r('receiptRemoveBuy')?.checked){const names=new Set(a.map(x=>String(x.name).trim()));buys=buys.filter(b=>!names.has(b.name))}save();render();closeReceiptV7();go('stock');alert(`${a.length}件を在庫へ反映しました`)};
const baseShow=showPremium;showPremium=function(k){if(k==='receipt')return openReceipt();if(k==='money'){const v=items.reduce((s,x)=>s+(Number.isFinite(x.purchaseTotal)?x.purchaseTotal:(x.price||0)*Math.max(1,x.qty||1)),0);return openM(`<button class="close" onclick="closeM()">閉じる</button><h2>💰 節約レポート</h2><div class="metrics"><div class="metric"><b>¥${v.toLocaleString()}</b><span class="muted">推定在庫金額</span></div><div class="metric"><b>${items.filter(x=>x.price>0).length}</b><span class="muted">価格記録</span></div><div class="metric"><b>${items.length}</b><span class="muted">登録品</span></div></div>`)}return baseShow(k)};
const badge=document.querySelector('.badge');if(badge)badge.textContent='試用版 v7';const prem=[...document.querySelectorAll('#pg-premium .premium')].find(x=>x.textContent.includes('レシート一括補充'));if(prem){const m=prem.querySelector('.meta');if(m)m.textContent='写真をOCR解析→確認→在庫反映'}
})();