/* あとこれ v11 - ホーム再設計 / カテゴリ色 / フッターナビ */
(()=>{
 const CAT={
  '食料品':{c:'#E87520',bg:'#FFF3E8',bd:'#FFD8B5',i:'🍚'},
  '日用品':{c:'#2878C8',bg:'#EAF4FF',bd:'#C9E2FA',i:'🧻'},
  '衛生・薬':{c:'#D64A55',bg:'#FFF0F1',bd:'#F6CDD1',i:'✚'},
  'ベビー':{c:'#D65A92',bg:'#FFF0F7',bd:'#F7CDE0',i:'👶'},
  '子ども':{c:'#A76A00',bg:'#FFF8D9',bd:'#F4E29A',i:'🧸'},
  '衣類':{c:'#7755C7',bg:'#F3EFFF',bd:'#DDD2FA',i:'👕'},
  '家電・生活用品':{c:'#596579',bg:'#F0F2F5',bd:'#D8DDE5',i:'🔋'},
  '防災':{c:'#27835A',bg:'#EAF8F0',bd:'#C9EAD7',i:'🛟'}
 };
 const css=`
 body{background:#eef1f5}.app{background:#f5f7fa}.content{padding-top:12px}
 #pg-home{margin:-2px -2px 0;padding:2px}
 .homeStatusCard{border-radius:22px;padding:16px;border:1px solid #dce5ef;background:linear-gradient(135deg,#edf8f2,#f8fcfa);box-shadow:0 4px 16px #2230470a}
 .homeStatusCard.attn{background:linear-gradient(135deg,#fff8e8,#fffdf7);border-color:#f4d99a}.homeStatusCard.dangerState{background:linear-gradient(135deg,#fff0f0,#fff8f8);border-color:#f3c3c3}
 .homeEyebrow{font-size:11px;font-weight:900;color:#607086;letter-spacing:.03em}.homeStatusTitle{display:flex;align-items:center;gap:7px;margin-top:4px;font-size:22px;font-weight:950}.homeStatusText{font-size:11px;color:#667085;margin-top:4px}
 .homeMetrics{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:10px}.homeMetric{border:1px solid var(--bd);background:var(--bg);border-radius:14px;padding:8px 5px;text-align:left;color:var(--c)}.homeMetric .mi{font-size:15px}.homeMetric b{display:block;font-size:20px;line-height:1.05;margin:3px 0}.homeMetric small{font-size:10px;font-weight:850;color:#566174}
 .homeBlock{background:#fff;border:1px solid #e1e6ed;border-radius:18px;padding:12px;margin-top:11px;box-shadow:0 3px 12px #22304708}.homeBlockHead{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:7px}.homeBlockTitle{font-size:14px;font-weight:950}.homeBlockSub{font-size:10px;color:#8a94a4}
 .homeUrgentList .row{border:0;border-bottom:1px solid #eef1f4;border-radius:0;margin:0;padding:9px 2px;background:transparent}.homeUrgentList .row:last-child{border-bottom:0}.homeUrgentList .expiryNear{border-left:4px solid #e34848!important;padding-left:8px!important;background:#fff8f8!important;border-radius:9px!important}
 .homeQuickGrid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.homeQuick{border:1px solid #cfe0f4;border-radius:13px;background:#f1f7ff;padding:9px;text-align:left;color:#185f9f;font-weight:900}.homeQuick strong{font-size:17px;margin-right:5px}.homeQuick span{font-size:11px}.homeQuick.bulk{background:#f3f0ff;border-color:#ddd3fa;color:#6848b4}.homeQuick.receipt{background:#f0f9f4;border-color:#cfe9da;color:#23724d}.homeQuick.buy{background:#fff6eb;border-color:#f5dcc0;color:#a45c0b}
 .homeCats{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.homeCat{border:1px solid var(--bd);background:var(--bg);border-radius:12px;padding:7px 3px;text-align:center;color:var(--c);min-width:0}.homeCat .ci{display:block;font-size:16px}.homeCat .cn{display:block;font-size:9px;font-weight:900;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:2px}.homeCat .cc{font-size:9px;color:#667085}
 .catMark{display:inline-flex;align-items:center;gap:4px;padding:2px 6px;border-radius:999px;background:var(--bg);color:var(--c);border:1px solid var(--bd);font-size:9px;font-weight:900;margin-top:3px}.catAccent{border-left:4px solid var(--c)!important}.catChip{border-color:var(--bd)!important;background:var(--bg)!important;color:var(--c)!important}.catChip.on{box-shadow:inset 0 0 0 1px var(--c);font-weight:950}
 .tabs{gap:0;border-top:1px solid #d7dde5;box-shadow:0 -4px 16px #22304712;padding-top:0;background:#fff}.tab{position:relative;border-right:1px solid #edf0f3!important;min-height:55px;padding:6px 1px 4px!important;font-weight:800}.tab:last-child{border-right:0!important}.tab b{height:24px;display:flex!important;align-items:center;justify-content:center}.tab.on{background:#edf5ff;color:#1268b3}.tab.on:before{content:'';position:absolute;left:20%;right:20%;top:0;height:3px;border-radius:0 0 4px 4px;background:#1677ff}.tab[data-p='add'] b{width:28px;height:28px;margin:-3px auto 0;border-radius:50%;background:#1677ff;color:#fff;font-size:19px}.tab[data-p='add'].on b{background:#0b63ce}.navBadge{position:absolute;top:3px;left:calc(50% + 7px);min-width:16px;height:16px;padding:0 4px;border-radius:999px;background:#e5484d;color:#fff;font-size:9px;font-weight:950;display:flex;align-items:center;justify-content:center;border:2px solid #fff}.navDot{position:absolute;top:6px;left:calc(50% + 8px);width:8px;height:8px;border-radius:50%;background:#e5484d;border:2px solid #fff}
 body.atk-density-ultra .homeStatusCard{padding:8px;border-radius:12px}.atk-density-ultra .homeStatusTitle{font-size:16px}.atk-density-ultra .homeMetrics{gap:3px;margin-top:5px}.atk-density-ultra .homeMetric{padding:4px 3px;border-radius:8px}.atk-density-ultra .homeMetric b{font-size:15px}.atk-density-ultra .homeBlock{padding:6px;margin-top:5px;border-radius:10px}.atk-density-ultra .homeBlockHead{margin-bottom:3px}.atk-density-ultra .homeQuickGrid,.atk-density-ultra .homeCats{gap:3px}.atk-density-ultra .homeQuick{padding:5px;border-radius:8px}.atk-density-ultra .homeCat{padding:4px 2px;border-radius:7px}.atk-density-ultra .tabs .tab{min-height:45px}
 `;
 const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function cv(cat){return CAT[cat]||CAT['家電・生活用品']}
 function vars(cat){const x=cv(cat);return `--c:${x.c};--bg:${x.bg};--bd:${x.bd}`}
 function days(exp){if(!exp)return 9999;const d=new Date(exp+'T00:00:00'),n=new Date();n.setHours(0,0,0,0);return Math.round((d-n)/86400000)}
 function stock(){try{return typeof items!=='undefined'&&Array.isArray(items)?items:[]}catch(e){return []}}
 function buy(){try{return typeof buys!=='undefined'&&Array.isArray(buys)?buys:[]}catch(e){return []}}
 function catCount(cat){return stock().filter(x=>x.cat===cat).length}
 function renderHomeV11(){
  const home=document.getElementById('pg-home');if(!home)return;
  const arr=stock(),bs=buy();const exp=arr.filter(x=>x.exp&&days(x.exp)<=3);const expired=arr.filter(x=>x.exp&&days(x.exp)<0);const pred=arr.filter(x=>Number(x.qty)<=1).length;
  const status=expired.length?'dangerState':(exp.length||bs.length?'attn':'');const icon=expired.length?'!':(exp.length||bs.length?'⚠':'✓');const title=expired.length?`${expired.length}件の期限切れがあります`:(exp.length||bs.length?`${exp.length+bs.length}件を確認`:'今日は急ぎなし');
  const urgent=exp.slice().sort((a,b)=>days(a.exp)-days(b.exp)).slice(0,5);
  const urgentHtml=urgent.length?urgent.map(x=>{const d=days(x.exp),c=cv(x.cat);return `<div class="row ${d<=3?'expiryNear':''}" style="${vars(x.cat)}"><div class="grow"><div class="name">${esc(x.name)}</div><span class="catMark" style="${vars(x.cat)}">${c.i} ${esc(x.cat)}</span></div><div style="text-align:right"><b>${esc(x.qty)}${esc(x.unit)}</b><div class="expiryBadge ${d<0?'expiryExpired':''}">${d<0?`期限切れ ${Math.abs(d)}日`:(d===0?'今日まで':`あと${d}日`)}</div></div></div>`}).join(''):`<div class="empty">期限が近いものはありません</div>`;
  const cats=Object.keys(CAT).map(cat=>{const c=cv(cat);return `<button class="homeCat" style="${vars(cat)}" onclick="goCatV11('${cat}')"><span class="ci">${c.i}</span><span class="cn">${esc(cat)}</span><span class="cc">${catCount(cat)}件</span></button>`}).join('');
  home.innerHTML=`<div class="homeStatusCard ${status}"><div class="homeEyebrow">今日のあとこれ</div><div class="homeStatusTitle"><span>${icon}</span><span>${title}</span></div><div class="homeStatusText">必要なことだけ上から確認できます</div><div class="homeMetrics"><button class="homeMetric" style="--c:#c43c3c;--bg:#fff0f0;--bd:#f3cccc" onclick="go('stock')"><span class="mi">⏰</span><b>${exp.length}</b><small>期限近い</small></button><button class="homeMetric" style="--c:#1769aa;--bg:#edf6ff;--bd:#cce2f5" onclick="go('buy')"><span class="mi">🛒</span><b>${bs.length}</b><small>買うもの</small></button><button class="homeMetric" style="--c:#7251b5;--bg:#f3efff;--bd:#ddd2fa" onclick="showPremium('predict')"><span class="mi">✦</span><b>${pred}</b><small>そろそろ</small></button></div></div>
  <div class="homeBlock"><div class="homeBlockHead"><div><div class="homeBlockTitle">要対応</div><div class="homeBlockSub">期限が近い順</div></div><button class="btn ghost" style="padding:5px 8px" onclick="go('stock')">在庫を見る</button></div><div class="homeUrgentList">${urgentHtml}</div></div>
  <div class="homeBlock"><div class="homeBlockHead"><div><div class="homeBlockTitle">すぐやる</div><div class="homeBlockSub">よく使う操作</div></div></div><div class="homeQuickGrid"><button class="homeQuick" onclick="go('add')"><strong>＋</strong><span>在庫追加</span></button><button class="homeQuick bulk" onclick="go('add');if(typeof openBulkAddV9==='function')openBulkAddV9()"><strong>⚡</strong><span>まとめて追加</span></button><button class="homeQuick receipt" onclick="showPremium('receipt')"><strong>🧾</strong><span>レシート補充</span></button><button class="homeQuick buy" onclick="go('buy')"><strong>🛒</strong><span>買い物</span></button></div></div>
  <div class="homeBlock"><div class="homeBlockHead"><div><div class="homeBlockTitle">カテゴリー</div><div class="homeBlockSub">色でひと目で判別</div></div></div><div class="homeCats">${cats}</div></div><div id="historyHomeV11"></div>`;
  renderHistoryHomeV11();updateNavV11();
 }
 function renderHistoryHomeV11(){const host=document.getElementById('historyHomeV11');if(!host)return;let h=[];try{h=JSON.parse(localStorage.getItem('atokoreHistoryV1')||'[]')}catch(e){};const rows=h.slice(0,2).map(x=>`<div class="historyMini"><div class="historyMiniIcon">${esc(x.icon||'✎')}</div><div class="grow"><div class="name">${esc(x.title)}</div><div class="historyDetail">${esc(x.detail)}</div></div></div>`).join('');host.innerHTML=`<div class="homeBlock"><div class="homeBlockHead"><div><div class="homeBlockTitle">最近の更新</div><div class="homeBlockSub">直近の操作</div></div><button class="btn ghost" style="padding:5px 8px" onclick="window.openAtokoreHistory?.()">すべて見る</button></div>${rows||'<div class="empty">まだ更新履歴はありません</div>'}</div>`}
 window.goCatV11=cat=>{try{filter=cat}catch(e){};go('stock');try{renderStock()}catch(e){};decorateRows()};
 function decorateRows(){document.querySelectorAll('#stockList .row').forEach(r=>{const txt=r.textContent||'';const x=stock().find(i=>txt.includes(i.name));if(!x)return;r.style.cssText+=`;${vars(x.cat)}`;r.classList.add('catAccent');if(!r.querySelector('.catMark')){const n=r.querySelector('.name');if(n){const c=cv(x.cat);n.insertAdjacentHTML('afterend',`<span class="catMark" style="${vars(x.cat)}">${c.i} ${esc(x.cat)}</span>`)}}});document.querySelectorAll('#catChips .chip').forEach(ch=>{const cat=Object.keys(CAT).find(c=>ch.textContent.includes(c));if(cat){ch.classList.add('catChip');ch.style.cssText+=`;${vars(cat)}`}})}
 function updateNavV11(){const b=buy().length;const exp=stock().filter(x=>x.exp&&days(x.exp)<=3).length;document.querySelectorAll('.navBadge,.navDot').forEach(x=>x.remove());const buyTab=document.querySelector('.tab[data-p="buy"]');if(b&&buyTab)buyTab.insertAdjacentHTML('beforeend',`<span class="navBadge">${b>99?'99+':b}</span>`);const stockTab=document.querySelector('.tab[data-p="stock"]');if(exp&&stockTab)stockTab.insertAdjacentHTML('beforeend','<span class="navDot"></span>')}
 function enhanceNav(){const labels={home:['⌂','ホーム'],stock:['📦','在庫'],add:['＋','追加'],buy:['🛒','買い物'],premium:['✦','Premium']};document.querySelectorAll('.tab').forEach(t=>{const p=t.dataset.p;if(labels[p])t.innerHTML=`<b>${labels[p][0]}</b>${labels[p][1]}`});updateNavV11()}
 window.renderHome=renderHomeV11;
 const baseRender=window.render;if(typeof baseRender==='function'){window.render=function(...a){const out=baseRender.apply(this,a);decorateRows();updateNavV11();return out}}
 const baseGo=window.go;if(typeof baseGo==='function'){window.go=function(p){const out=baseGo.apply(this,arguments);setTimeout(()=>{if(p==='home')renderHomeV11();else decorateRows();updateNavV11()},0);return out}}
 enhanceNav();renderHomeV11();decorateRows();
 const badge=document.querySelector('.badge');if(badge)badge.textContent='試用版 v11';
})();
